name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

# This permission block fixes the exit code 128 error
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Bumped to v4 to fix the Node.js warning
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        with:
          github_user_name: d-rupam
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Bumped to v4 to fix the Node.js warning
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
